In [42]:
import gaussian_mixtures as gm
import pandas as pd
import numpy as np
import importlib
importlib.reload(gm)

<module 'gaussian_mixtures' from '/Users/Olivia.Dalglish/personal/uiuc/psl/coding_4/gaussian_mixtures.py'>

In [38]:
data = np.loadtxt("faithful.dat", skiprows=1)[:, 1:]

n, p = data.shape

### G = 2

In [43]:
G = 2

# initialize mixing weights
p1 = 10 / n
p2 = 1 - p1
prob = np.array([p1, p2])

mu1 = np.mean(data[:10], axis=0)
mu2 = np.mean(data[10:], axis=0)
means = np.column_stack((mu1, mu2))

# initialize covariance matrix
Sigma = np.zeros((p, p))
for i in range(10):
    diff = data[i] - mu1
    Sigma += np.outer(diff, diff)
for i in range(10, n):
    diff = data[i] - mu2
    Sigma += np.outer(diff, diff)
Sigma /= n

itmax = 20

final_prob, final_means, final_Sigma, log_likelihood = gm.myEM(data, G, prob, means, Sigma, itmax)

print("Final probabilities")
print(final_prob)

print("Final means")
print(final_means)

print("Final cov matrix")
print(final_Sigma)

print("log likelihood")
print(log_likelihood)

Final probabilities
[0.04297883 0.95702117]
Final means
[[ 3.49564188  3.48743016]
 [76.79789154 70.63205853]]
Final cov matrix
[[  1.29793612  13.92433626]
 [ 13.92433626 182.58009247]]
log likelihood
-20807.316025787797


### G = 3

In [39]:
G = 3

# initialize mixing weights
p1 = 10 / n
p2 = 20 / n
p3 = 1 - p1 - p2
prob = np.array([p1, p2, p3])

# initialize means
mu1 = np.mean(data[:10], axis=0)
mu2 = np.mean(data[10:30], axis=0)
mu3 = np.mean(data[30:], axis=0)
means = np.column_stack((mu1, mu2, mu3))

# initialize covariance matrix
Sigma = np.zeros((p, p))
for i in range(10):
    diff = data[i] - mu1
    Sigma += np.outer(diff, diff)
for i in range(10, 30):
    diff = data[i] - mu2
    Sigma += np.outer(diff, diff)
for i in range(30, n):
    diff = data[i] - mu3
    Sigma += np.outer(diff, diff)
Sigma /= n  # Shape (p, p)

itmax = 20

final_prob, final_means, final_Sigma, log_likelihood = gm.myEM(data, G, prob, means, Sigma, itmax)

print("Final probabilities")
print(final_prob)

print("Final means")
print(final_means)

print("Final cov matrix")
print(final_Sigma)

print("log likelihood")
print(log_likelihood)

Final probabilities
[0.04363422 0.07718656 0.87917922]
Final means
[[ 3.51006918  2.81616674  3.54564083]
 [77.10563811 63.35752634 71.25084801]]
Final cov matrix
[[  1.26015772  13.51153756]
 [ 13.51153756 177.96419105]]
log likelihood
-1289.3509588627385
